apiVersion: v1 #apiversion of POD object
kind: Pod #type of object
metadata: #addional info about the POD
  name: demopod
  labels:
    app.kubernetes.io/name: demopod
    env: qa
    project: delivery
spec:
  containers:
  - name: democont1
    image: nginxdemos/hello:0.4
    ports:
      - containerPort: 80
